spring.application.name=Fiserv_Kafka_Producer
spring.spark.structured.streaming.event.recieving.topic=fiserv-coforge-event-produced-spark-stream
spring.spark.structured.streaming.with.window.output=fiserv-coforge-event-spark-stream-with-window
spring.spark.structured.streaming.without.window.output=fiserv-coforge-event-from-spark-stream-without-window
spring.kafka.bootstrap-servers=localhost:9092
server.port=8080
